[2023-06-23T01:59:36.330+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:58:31.696804+00:00 [queued]>
[2023-06-23T01:59:36.336+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:58:31.696804+00:00 [queued]>
[2023-06-23T01:59:36.337+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T01:59:36.338+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-23T01:59:36.338+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T01:59:36.346+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-23 01:58:31.696804+00:00
[2023-06-23T01:59:36.350+0000] {standard_task_runner.py:55} INFO - Started process 24593 to run task
[2023-06-23T01:59:36.353+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_run', 'scheduled__2023-06-23T01:58:31.696804+00:00', '--job-id', '2666', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmpwtaiojiq']
[2023-06-23T01:59:36.354+0000] {standard_task_runner.py:83} INFO - Job 2666: Subtask dbt_run
[2023-06-23T01:59:36.410+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:58:31.696804+00:00 [running]> on host 62cfed75eae1
[2023-06-23T01:59:36.464+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-23T01:58:31.696804+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-23T01:58:31.696804+00:00
[2023-06-23T01:59:36.466+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-23T01:59:36.466+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/ticketmaster_transformation && dbt run']
[2023-06-23T01:59:36.475+0000] {subprocess.py:86} INFO - Output:
[2023-06-23T01:59:37.874+0000] {subprocess.py:93} INFO - [0m01:59:37  Running with dbt=1.5.1
[2023-06-23T01:59:38.439+0000] {subprocess.py:93} INFO - [0m01:59:38  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 356 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-23T01:59:38.442+0000] {subprocess.py:93} INFO - [0m01:59:38
[2023-06-23T01:59:39.100+0000] {subprocess.py:93} INFO - [0m01:59:39  Concurrency: 4 threads (target='dev')
[2023-06-23T01:59:39.102+0000] {subprocess.py:93} INFO - [0m01:59:39
[2023-06-23T01:59:39.113+0000] {subprocess.py:93} INFO - [0m01:59:39  1 of 4 START sql table model twitter_kafka_pyspark_test.distinct_data .......... [RUN]
[2023-06-23T01:59:39.115+0000] {subprocess.py:93} INFO - [0m01:59:39  2 of 4 START sql table model twitter_kafka_pyspark_test.dm_events .............. [RUN]
[2023-06-23T01:59:39.117+0000] {subprocess.py:93} INFO - [0m01:59:39  3 of 4 START sql table model twitter_kafka_pyspark_test.my_first_dbt_model ..... [RUN]
[2023-06-23T01:59:41.701+0000] {subprocess.py:93} INFO - [0m01:59:41  BigQuery adapter: https://console.cloud.google.com/bigquery?project=global-maxim-338114&j=bq:US:08a26c54-f4dc-4d38-b193-50d4900c6ecc&page=queryresults
[2023-06-23T01:59:41.709+0000] {subprocess.py:93} INFO - [0m01:59:41  2 of 4 ERROR creating sql table model twitter_kafka_pyspark_test.dm_events ..... [[31mERROR[0m in 2.59s]
[2023-06-23T01:59:41.823+0000] {subprocess.py:93} INFO - [0m01:59:41  3 of 4 OK created sql table model twitter_kafka_pyspark_test.my_first_dbt_model  [[32mCREATE TABLE (2.0 rows, 0 processed)[0m in 2.70s]
[2023-06-23T01:59:41.828+0000] {subprocess.py:93} INFO - [0m01:59:41  4 of 4 START sql view model twitter_kafka_pyspark_test.my_second_dbt_model ..... [RUN]
[2023-06-23T01:59:41.858+0000] {subprocess.py:93} INFO - [0m01:59:41  1 of 4 OK created sql table model twitter_kafka_pyspark_test.distinct_data ..... [[32mCREATE TABLE (1.0 rows, 0 processed)[0m in 2.72s]
[2023-06-23T01:59:42.874+0000] {subprocess.py:93} INFO - [0m01:59:42  4 of 4 OK created sql view model twitter_kafka_pyspark_test.my_second_dbt_model  [[32mCREATE VIEW (0 processed)[0m in 1.04s]
[2023-06-23T01:59:42.984+0000] {subprocess.py:93} INFO - [0m01:59:42
[2023-06-23T01:59:42.986+0000] {subprocess.py:93} INFO - [0m01:59:42  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 4.54 seconds (4.54s).
[2023-06-23T01:59:43.012+0000] {subprocess.py:93} INFO - [0m01:59:43
[2023-06-23T01:59:43.015+0000] {subprocess.py:93} INFO - [0m01:59:43  [31mCompleted with 1 error and 0 warnings:[0m
[2023-06-23T01:59:43.018+0000] {subprocess.py:93} INFO - [0m01:59:43
[2023-06-23T01:59:43.020+0000] {subprocess.py:93} INFO - [0m01:59:43  [33mDatabase Error in model dm_events (models/core/dm_events.sql)[0m
[2023-06-23T01:59:43.021+0000] {subprocess.py:93} INFO - [0m01:59:43    Unrecognized name: event_id at [14:8]
[2023-06-23T01:59:43.023+0000] {subprocess.py:93} INFO - [0m01:59:43    compiled Code at target/run/ticketmaster_transformation/models/core/dm_events.sql
[2023-06-23T01:59:43.024+0000] {subprocess.py:93} INFO - [0m01:59:43
[2023-06-23T01:59:43.026+0000] {subprocess.py:93} INFO - [0m01:59:43  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
[2023-06-23T01:59:43.605+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-23T01:59:43.643+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-23T01:59:43.648+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_run, execution_date=20230623T015831, start_date=20230623T015936, end_date=20230623T015943
[2023-06-23T01:59:43.664+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2666 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 24593)
[2023-06-23T01:59:43.683+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-23T01:59:43.715+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
