[2023-06-22T18:45:22.713+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-22T18:44:19.278058+00:00 [queued]>
[2023-06-22T18:45:22.720+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-22T18:44:19.278058+00:00 [queued]>
[2023-06-22T18:45:22.720+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-22T18:45:22.721+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-22T18:45:22.721+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-22T18:45:22.729+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-22 18:44:19.278058+00:00
[2023-06-22T18:45:22.733+0000] {standard_task_runner.py:55} INFO - Started process 17400 to run task
[2023-06-22T18:45:22.736+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_run', 'scheduled__2023-06-22T18:44:19.278058+00:00', '--job-id', '2014', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmpjc0gia8z']
[2023-06-22T18:45:22.737+0000] {standard_task_runner.py:83} INFO - Job 2014: Subtask dbt_run
[2023-06-22T18:45:22.791+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-22T18:44:19.278058+00:00 [running]> on host 62cfed75eae1
[2023-06-22T18:45:22.841+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-22T18:44:19.278058+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-22T18:44:19.278058+00:00
[2023-06-22T18:45:22.843+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-22T18:45:22.843+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/ticketmaster_transformation && dbt run']
[2023-06-22T18:45:22.853+0000] {subprocess.py:86} INFO - Output:
[2023-06-22T18:45:24.079+0000] {subprocess.py:93} INFO - [0m18:45:24  Running with dbt=1.5.1
[2023-06-22T18:45:24.539+0000] {subprocess.py:93} INFO - [0m18:45:24  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 356 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-22T18:45:24.542+0000] {subprocess.py:93} INFO - [0m18:45:24
[2023-06-22T18:55:56.088+0000] {subprocess.py:93} INFO - [0m18:55:56
[2023-06-22T18:55:56.092+0000] {subprocess.py:93} INFO - [0m18:55:56  Finished running  in 0 hours 10 minutes and 31.54 seconds (631.54s).
[2023-06-22T18:55:56.094+0000] {subprocess.py:93} INFO - [0m18:55:56  Encountered an error:
[2023-06-22T18:55:56.095+0000] {subprocess.py:93} INFO - Runtime Error
[2023-06-22T18:55:56.096+0000] {subprocess.py:93} INFO -   Deadline of 600.0s exceeded while calling target function, last exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2023-06-22T18:55:56.645+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-06-22T18:55:56.665+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-06-22T18:55:56.676+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_run, execution_date=20230622T184419, start_date=20230622T184522, end_date=20230622T185556
[2023-06-22T18:55:56.693+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2014 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 17400)
[2023-06-22T18:55:56.721+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-22T18:55:56.740+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
