[2023-05-13T22:00:25.250+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ny_taxi_local.create_directory.get_bash_var manual__2023-05-13T22:00:23.648284+00:00 [queued]>
[2023-05-13T22:00:25.261+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ny_taxi_local.create_directory.get_bash_var manual__2023-05-13T22:00:23.648284+00:00 [queued]>
[2023-05-13T22:00:25.262+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T22:00:25.262+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-13T22:00:25.263+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T22:00:25.274+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): create_directory.get_bash_var> on 2023-05-13 22:00:23.648284+00:00
[2023-05-13T22:00:25.284+0000] {standard_task_runner.py:55} INFO - Started process 2024 to run task
[2023-05-13T22:00:25.292+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ny_taxi_local', 'create_directory.get_bash_var', 'manual__2023-05-13T22:00:23.648284+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/fetch_and_upload.py', '--cfg-path', '/tmp/tmpy923otv2']
[2023-05-13T22:00:25.295+0000] {standard_task_runner.py:83} INFO - Job 62: Subtask create_directory.get_bash_var
[2023-05-13T22:00:25.412+0000] {task_command.py:389} INFO - Running <TaskInstance: ny_taxi_local.create_directory.get_bash_var manual__2023-05-13T22:00:23.648284+00:00 [running]> on host fdfc81637e26
[2023-05-13T22:00:25.489+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ny_taxi_local
AIRFLOW_CTX_TASK_ID=create_directory.get_bash_var
AIRFLOW_CTX_EXECUTION_DATE=2023-05-13T22:00:23.648284+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-13T22:00:23.648284+00:00
[2023-05-13T22:00:25.492+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-13T22:00:25.493+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'The run_id is: {run_id}']
[2023-05-13T22:00:25.504+0000] {subprocess.py:86} INFO - Output:
[2023-05-13T22:00:25.507+0000] {subprocess.py:93} INFO - /bin/bash: line 1: The: command not found
[2023-05-13T22:00:25.509+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-05-13T22:00:25.520+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_and_upload.py", line 49, in get_bash_var
    return op.execute(context={})
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-05-13T22:00:25.526+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ny_taxi_local, task_id=create_directory.get_bash_var, execution_date=20230513T220023, start_date=20230513T220025, end_date=20230513T220025
[2023-05-13T22:00:25.534+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 62 for task create_directory.get_bash_var (Bash command failed. The command returned a non-zero exit code 127.; 2024)
[2023-05-13T22:00:25.581+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-13T22:00:25.599+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
