[2023-06-22T11:47:18.412+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-22T11:46:13.997128+00:00 [queued]>
[2023-06-22T11:47:18.419+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-22T11:46:13.997128+00:00 [queued]>
[2023-06-22T11:47:18.419+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-22T11:47:18.420+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-22T11:47:18.420+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-22T11:47:18.428+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-22 11:46:13.997128+00:00
[2023-06-22T11:47:18.432+0000] {standard_task_runner.py:55} INFO - Started process 16048 to run task
[2023-06-22T11:47:18.435+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_run', 'scheduled__2023-06-22T11:46:13.997128+00:00', '--job-id', '1862', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmp9gnlwj2a']
[2023-06-22T11:47:18.436+0000] {standard_task_runner.py:83} INFO - Job 1862: Subtask dbt_run
[2023-06-22T11:47:18.489+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-22T11:46:13.997128+00:00 [running]> on host 62cfed75eae1
[2023-06-22T11:47:18.539+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-22T11:46:13.997128+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-22T11:46:13.997128+00:00
[2023-06-22T11:47:18.540+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-22T11:47:18.541+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/ticketmaster_transformation && dbt run']
[2023-06-22T11:47:18.549+0000] {subprocess.py:86} INFO - Output:
[2023-06-22T11:47:20.311+0000] {subprocess.py:93} INFO - [0m11:47:20  Running with dbt=1.5.1
[2023-06-22T11:47:20.883+0000] {subprocess.py:93} INFO - [0m11:47:20  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 356 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-22T11:47:20.886+0000] {subprocess.py:93} INFO - [0m11:47:20
[2023-06-22T11:47:21.665+0000] {subprocess.py:93} INFO - [0m11:47:21  Concurrency: 4 threads (target='dev')
[2023-06-22T11:47:21.666+0000] {subprocess.py:93} INFO - [0m11:47:21
[2023-06-22T11:47:21.676+0000] {subprocess.py:93} INFO - [0m11:47:21  1 of 4 START sql table model twitter_kafka_pyspark_test.distinct_data .......... [RUN]
[2023-06-22T11:47:21.678+0000] {subprocess.py:93} INFO - [0m11:47:21  2 of 4 START sql table model twitter_kafka_pyspark_test.dm_events .............. [RUN]
[2023-06-22T11:47:21.682+0000] {subprocess.py:93} INFO - [0m11:47:21  3 of 4 START sql table model twitter_kafka_pyspark_test.my_first_dbt_model ..... [RUN]
[2023-06-22T11:47:25.422+0000] {subprocess.py:93} INFO - [0m11:47:25  2 of 4 OK created sql table model twitter_kafka_pyspark_test.dm_events ......... [[32mCREATE TABLE (1.3k rows, 178.2 KiB processed)[0m in 3.73s]
[2023-06-22T12:02:02.941+0000] {subprocess.py:93} INFO - [0m12:02:02  3 of 4 OK created sql table model twitter_kafka_pyspark_test.my_first_dbt_model  [[32mCREATE TABLE (2.0 rows, 0 processed)[0m in 881.25s]
[2023-06-22T12:02:02.948+0000] {subprocess.py:93} INFO - [0m12:02:02  4 of 4 START sql view model twitter_kafka_pyspark_test.my_second_dbt_model ..... [RUN]
[2023-06-22T12:02:04.252+0000] {subprocess.py:93} INFO - [0m12:02:04  4 of 4 OK created sql view model twitter_kafka_pyspark_test.my_second_dbt_model  [[32mCREATE VIEW (0 processed)[0m in 1.30s]
[2023-06-22T12:02:06.955+0000] {subprocess.py:93} INFO - [0m12:02:06  [31mUnhandled error while executing [0m
[2023-06-22T12:02:06.957+0000] {subprocess.py:93} INFO - Deadline of 600.0s exceeded while calling target function, last exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2023-06-22T12:02:06.977+0000] {subprocess.py:93} INFO - [0m12:02:06  1 of 4 ERROR creating sql table model twitter_kafka_pyspark_test.distinct_data . [[31mERROR[0m in 885.29s]
[2023-06-22T12:02:07.104+0000] {subprocess.py:93} INFO - [0m12:02:07
[2023-06-22T12:02:07.106+0000] {subprocess.py:93} INFO - [0m12:02:07  Finished running 3 table models, 1 view model in 0 hours 14 minutes and 46.22 seconds (886.22s).
[2023-06-22T12:02:07.127+0000] {subprocess.py:93} INFO - [0m12:02:07
[2023-06-22T12:02:07.128+0000] {subprocess.py:93} INFO - [0m12:02:07  [31mCompleted with 1 error and 0 warnings:[0m
[2023-06-22T12:02:07.130+0000] {subprocess.py:93} INFO - [0m12:02:07
[2023-06-22T12:02:07.131+0000] {subprocess.py:93} INFO - [0m12:02:07  [33mDeadline of 600.0s exceeded while calling target function, last exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[2023-06-22T12:02:07.133+0000] {subprocess.py:93} INFO - [0m12:02:07
[2023-06-22T12:02:07.134+0000] {subprocess.py:93} INFO - [0m12:02:07  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
[2023-06-22T12:02:07.612+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-22T12:02:07.636+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-22T12:02:07.642+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_run, execution_date=20230622T114613, start_date=20230622T114718, end_date=20230622T120207
[2023-06-22T12:02:07.681+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1862 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 16048)
[2023-06-22T12:02:07.718+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-22T12:02:07.737+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
