[2023-06-23T01:52:35.337+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:51:31.696804+00:00 [queued]>
[2023-06-23T01:52:35.344+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:51:31.696804+00:00 [queued]>
[2023-06-23T01:52:35.345+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T01:52:35.345+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-23T01:52:35.346+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T01:52:35.355+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-23 01:51:31.696804+00:00
[2023-06-23T01:52:35.359+0000] {standard_task_runner.py:55} INFO - Started process 24245 to run task
[2023-06-23T01:52:35.362+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_run', 'scheduled__2023-06-23T01:51:31.696804+00:00', '--job-id', '2638', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmp5dt6g93b']
[2023-06-23T01:52:35.363+0000] {standard_task_runner.py:83} INFO - Job 2638: Subtask dbt_run
[2023-06-23T01:52:35.420+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:51:31.696804+00:00 [running]> on host 62cfed75eae1
[2023-06-23T01:52:35.474+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-23T01:51:31.696804+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-23T01:51:31.696804+00:00
[2023-06-23T01:52:35.476+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-23T01:52:35.477+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/ticketmaster_transformation && dbt run']
[2023-06-23T01:52:35.486+0000] {subprocess.py:86} INFO - Output:
[2023-06-23T01:52:36.854+0000] {subprocess.py:93} INFO - [0m01:52:36  Running with dbt=1.5.1
[2023-06-23T01:52:37.418+0000] {subprocess.py:93} INFO - [0m01:52:37  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 356 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-23T01:52:37.421+0000] {subprocess.py:93} INFO - [0m01:52:37
[2023-06-23T01:52:38.194+0000] {subprocess.py:93} INFO - [0m01:52:38  Concurrency: 4 threads (target='dev')
[2023-06-23T01:52:38.202+0000] {subprocess.py:93} INFO - [0m01:52:38
[2023-06-23T01:52:38.220+0000] {subprocess.py:93} INFO - [0m01:52:38  1 of 4 START sql table model twitter_kafka_pyspark_test.distinct_data .......... [RUN]
[2023-06-23T01:52:38.227+0000] {subprocess.py:93} INFO - [0m01:52:38  3 of 4 START sql table model twitter_kafka_pyspark_test.my_first_dbt_model ..... [RUN]
[2023-06-23T01:52:38.230+0000] {subprocess.py:93} INFO - [0m01:52:38  2 of 4 START sql table model twitter_kafka_pyspark_test.dm_events .............. [RUN]
[2023-06-23T01:52:40.379+0000] {subprocess.py:93} INFO - [0m01:52:40  BigQuery adapter: https://console.cloud.google.com/bigquery?project=global-maxim-338114&j=bq:US:06a7922b-e08f-4694-8ed2-dc03492a70c1&page=queryresults
[2023-06-23T01:52:40.403+0000] {subprocess.py:93} INFO - [0m01:52:40  2 of 4 ERROR creating sql table model twitter_kafka_pyspark_test.dm_events ..... [[31mERROR[0m in 2.16s]
[2023-06-23T01:52:40.967+0000] {subprocess.py:93} INFO - [0m01:52:40  3 of 4 OK created sql table model twitter_kafka_pyspark_test.my_first_dbt_model  [[32mCREATE TABLE (2.0 rows, 0 processed)[0m in 2.73s]
[2023-06-23T01:52:40.982+0000] {subprocess.py:93} INFO - [0m01:52:40  4 of 4 START sql view model twitter_kafka_pyspark_test.my_second_dbt_model ..... [RUN]
[2023-06-23T01:52:41.101+0000] {subprocess.py:93} INFO - [0m01:52:41  1 of 4 OK created sql table model twitter_kafka_pyspark_test.distinct_data ..... [[32mCREATE TABLE (1.0 rows, 0 processed)[0m in 2.87s]
[2023-06-23T01:52:41.881+0000] {subprocess.py:93} INFO - [0m01:52:41  4 of 4 OK created sql view model twitter_kafka_pyspark_test.my_second_dbt_model  [[32mCREATE VIEW (0 processed)[0m in 0.90s]
[2023-06-23T01:52:41.981+0000] {subprocess.py:93} INFO - [0m01:52:41
[2023-06-23T01:52:41.983+0000] {subprocess.py:93} INFO - [0m01:52:41  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 4.56 seconds (4.56s).
[2023-06-23T01:52:42.010+0000] {subprocess.py:93} INFO - [0m01:52:42
[2023-06-23T01:52:42.012+0000] {subprocess.py:93} INFO - [0m01:52:42  [31mCompleted with 1 error and 0 warnings:[0m
[2023-06-23T01:52:42.013+0000] {subprocess.py:93} INFO - [0m01:52:42
[2023-06-23T01:52:42.014+0000] {subprocess.py:93} INFO - [0m01:52:42  [33mDatabase Error in model dm_events (models/core/dm_events.sql)[0m
[2023-06-23T01:52:42.016+0000] {subprocess.py:93} INFO - [0m01:52:42    Unrecognized name: event_id at [14:8]
[2023-06-23T01:52:42.017+0000] {subprocess.py:93} INFO - [0m01:52:42    compiled Code at target/run/ticketmaster_transformation/models/core/dm_events.sql
[2023-06-23T01:52:42.019+0000] {subprocess.py:93} INFO - [0m01:52:42
[2023-06-23T01:52:42.021+0000] {subprocess.py:93} INFO - [0m01:52:42  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
[2023-06-23T01:52:42.482+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-23T01:52:42.496+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-23T01:52:42.500+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_run, execution_date=20230623T015131, start_date=20230623T015235, end_date=20230623T015242
[2023-06-23T01:52:42.513+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2638 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 24245)
[2023-06-23T01:52:42.547+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-23T01:52:42.562+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
