[2023-06-22T06:32:18.914+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-22T05:54:35.876920+00:00 [queued]>
[2023-06-22T06:32:18.921+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-22T05:54:35.876920+00:00 [queued]>
[2023-06-22T06:32:18.921+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-22T06:32:18.922+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-22T06:32:18.922+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-22T06:32:18.933+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-22 05:54:35.876920+00:00
[2023-06-22T06:32:18.937+0000] {standard_task_runner.py:55} INFO - Started process 15764 to run task
[2023-06-22T06:32:18.940+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_run', 'scheduled__2023-06-22T05:54:35.876920+00:00', '--job-id', '1830', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmp6mo7yid8']
[2023-06-22T06:32:18.941+0000] {standard_task_runner.py:83} INFO - Job 1830: Subtask dbt_run
[2023-06-22T06:32:19.000+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-22T05:54:35.876920+00:00 [running]> on host 62cfed75eae1
[2023-06-22T06:32:19.061+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-22T05:54:35.876920+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-22T05:54:35.876920+00:00
[2023-06-22T06:32:19.062+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-22T06:32:19.063+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/ticketmaster_transformation && dbt run']
[2023-06-22T06:32:19.073+0000] {subprocess.py:86} INFO - Output:
[2023-06-22T06:32:20.489+0000] {subprocess.py:93} INFO - [0m06:32:20  Running with dbt=1.5.1
[2023-06-22T06:32:21.017+0000] {subprocess.py:93} INFO - [0m06:32:21  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 356 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-22T06:32:21.020+0000] {subprocess.py:93} INFO - [0m06:32:21
[2023-06-22T06:32:21.943+0000] {subprocess.py:93} INFO - [0m06:32:21  Concurrency: 4 threads (target='dev')
[2023-06-22T06:32:21.945+0000] {subprocess.py:93} INFO - [0m06:32:21
[2023-06-22T06:32:21.955+0000] {subprocess.py:93} INFO - [0m06:32:21  1 of 4 START sql table model twitter_kafka_pyspark_test.distinct_data .......... [RUN]
[2023-06-22T06:32:21.957+0000] {subprocess.py:93} INFO - [0m06:32:21  2 of 4 START sql table model twitter_kafka_pyspark_test.dm_events .............. [RUN]
[2023-06-22T06:32:21.959+0000] {subprocess.py:93} INFO - [0m06:32:21  3 of 4 START sql table model twitter_kafka_pyspark_test.my_first_dbt_model ..... [RUN]
[2023-06-22T06:32:38.966+0000] {subprocess.py:93} INFO - [0m06:32:38  2 of 4 OK created sql table model twitter_kafka_pyspark_test.dm_events ......... [[32mCREATE TABLE (1.3k rows, 178.2 KiB processed)[0m in 17.00s]
[2023-06-22T06:32:40.107+0000] {subprocess.py:93} INFO - [0m06:32:40  1 of 4 OK created sql table model twitter_kafka_pyspark_test.distinct_data ..... [[32mCREATE TABLE (1.1k rows, 638.3 KiB processed)[0m in 18.14s]
[2023-06-22T06:32:40.115+0000] {subprocess.py:93} INFO - [0m06:32:40  3 of 4 OK created sql table model twitter_kafka_pyspark_test.my_first_dbt_model  [[32mCREATE TABLE (2.0 rows, 0 processed)[0m in 18.14s]
[2023-06-22T06:32:40.122+0000] {subprocess.py:93} INFO - [0m06:32:40  4 of 4 START sql view model twitter_kafka_pyspark_test.my_second_dbt_model ..... [RUN]
[2023-06-22T07:08:25.369+0000] {subprocess.py:93} INFO - [0m07:08:25  4 of 4 ERROR creating sql view model twitter_kafka_pyspark_test.my_second_dbt_model  [[31mERROR[0m in 2145.24s]
[2023-06-22T07:08:25.420+0000] {subprocess.py:93} INFO - [0m07:08:25
[2023-06-22T07:08:25.422+0000] {subprocess.py:93} INFO - [0m07:08:25  Finished running 3 table models, 1 view model in 0 hours 36 minutes and 4.40 seconds (2164.40s).
[2023-06-22T07:08:25.439+0000] {subprocess.py:93} INFO - [0m07:08:25
[2023-06-22T07:08:25.442+0000] {subprocess.py:93} INFO - [0m07:08:25  [31mCompleted with 1 error and 0 warnings:[0m
[2023-06-22T07:08:25.443+0000] {subprocess.py:93} INFO - [0m07:08:25
[2023-06-22T07:08:25.444+0000] {subprocess.py:93} INFO - [0m07:08:25  [33mRuntime Error in model my_second_dbt_model (models/example/my_second_dbt_model.sql)[0m
[2023-06-22T07:08:25.445+0000] {subprocess.py:93} INFO - [0m07:08:25    Deadline of 600.0s exceeded while calling target function, last exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2023-06-22T07:08:25.446+0000] {subprocess.py:93} INFO - [0m07:08:25
[2023-06-22T07:08:25.448+0000] {subprocess.py:93} INFO - [0m07:08:25  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
[2023-06-22T07:08:26.047+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-22T07:08:26.070+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-22T07:08:26.080+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_run, execution_date=20230622T055435, start_date=20230622T063218, end_date=20230622T070826
[2023-06-22T07:08:26.102+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1830 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 15764)
[2023-06-22T07:08:26.133+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-22T07:08:26.150+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
