[2023-06-23T02:30:56.906+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:29:52.899435+00:00 [queued]>
[2023-06-23T02:30:56.912+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:29:52.899435+00:00 [queued]>
[2023-06-23T02:30:56.913+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T02:30:56.913+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-23T02:30:56.914+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T02:30:56.921+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-23 02:29:52.899435+00:00
[2023-06-23T02:30:56.925+0000] {standard_task_runner.py:55} INFO - Started process 26203 to run task
[2023-06-23T02:30:56.928+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_run', 'scheduled__2023-06-23T02:29:52.899435+00:00', '--job-id', '2794', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmpdoax7tag']
[2023-06-23T02:30:56.929+0000] {standard_task_runner.py:83} INFO - Job 2794: Subtask dbt_run
[2023-06-23T02:30:56.980+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:29:52.899435+00:00 [running]> on host 62cfed75eae1
[2023-06-23T02:30:57.032+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-23T02:29:52.899435+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-23T02:29:52.899435+00:00
[2023-06-23T02:30:57.033+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-23T02:30:57.034+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/ticketmaster_transformation && dbt run']
[2023-06-23T02:30:57.042+0000] {subprocess.py:86} INFO - Output:
[2023-06-23T02:30:58.291+0000] {subprocess.py:93} INFO - [0m02:30:58  Running with dbt=1.5.1
[2023-06-23T02:30:58.798+0000] {subprocess.py:93} INFO - [0m02:30:58  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 356 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-23T02:30:58.801+0000] {subprocess.py:93} INFO - [0m02:30:58
[2023-06-23T02:30:59.728+0000] {subprocess.py:93} INFO - [0m02:30:59  Concurrency: 4 threads (target='dev')
[2023-06-23T02:30:59.731+0000] {subprocess.py:93} INFO - [0m02:30:59
[2023-06-23T02:30:59.748+0000] {subprocess.py:93} INFO - [0m02:30:59  1 of 4 START sql table model twitter_kafka_pyspark_test.distinct_data .......... [RUN]
[2023-06-23T02:30:59.751+0000] {subprocess.py:93} INFO - [0m02:30:59  2 of 4 START sql table model twitter_kafka_pyspark_test.dm_events .............. [RUN]
[2023-06-23T02:30:59.753+0000] {subprocess.py:93} INFO - [0m02:30:59  3 of 4 START sql table model twitter_kafka_pyspark_test.my_first_dbt_model ..... [RUN]
[2023-06-23T02:31:02.354+0000] {subprocess.py:93} INFO - [0m02:31:02  3 of 4 OK created sql table model twitter_kafka_pyspark_test.my_first_dbt_model  [[32mCREATE TABLE (2.0 rows, 0 processed)[0m in 2.59s]
[2023-06-23T02:31:02.356+0000] {subprocess.py:93} INFO - [0m02:31:02  2 of 4 OK created sql table model twitter_kafka_pyspark_test.dm_events ......... [[32mCREATE TABLE (217.0 rows, 32.0 KiB processed)[0m in 2.59s]
[2023-06-23T02:31:02.365+0000] {subprocess.py:93} INFO - [0m02:31:02  4 of 4 START sql view model twitter_kafka_pyspark_test.my_second_dbt_model ..... [RUN]
[2023-06-23T02:31:03.095+0000] {subprocess.py:93} INFO - [0m02:31:03  BigQuery adapter: https://console.cloud.google.com/bigquery?project=global-maxim-338114&j=bq:US:3f3a064a-1ddd-4c60-83a2-13abc1c95b9d&page=queryresults
[2023-06-23T02:31:03.132+0000] {subprocess.py:93} INFO - [0m02:31:03  1 of 4 ERROR creating sql table model twitter_kafka_pyspark_test.distinct_data . [[31mERROR[0m in 3.37s]
[2023-06-23T02:31:03.323+0000] {subprocess.py:93} INFO - [0m02:31:03  4 of 4 OK created sql view model twitter_kafka_pyspark_test.my_second_dbt_model  [[32mCREATE VIEW (0 processed)[0m in 0.95s]
[2023-06-23T02:31:03.432+0000] {subprocess.py:93} INFO - [0m02:31:03
[2023-06-23T02:31:03.434+0000] {subprocess.py:93} INFO - [0m02:31:03  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 4.63 seconds (4.63s).
[2023-06-23T02:31:03.460+0000] {subprocess.py:93} INFO - [0m02:31:03
[2023-06-23T02:31:03.461+0000] {subprocess.py:93} INFO - [0m02:31:03  [31mCompleted with 1 error and 0 warnings:[0m
[2023-06-23T02:31:03.462+0000] {subprocess.py:93} INFO - [0m02:31:03
[2023-06-23T02:31:03.463+0000] {subprocess.py:93} INFO - [0m02:31:03  [33mDatabase Error in model distinct_data (models/core/distinct_data.sql)[0m
[2023-06-23T02:31:03.464+0000] {subprocess.py:93} INFO - [0m02:31:03    Type not found: FLOAT at [46:21]
[2023-06-23T02:31:03.466+0000] {subprocess.py:93} INFO - [0m02:31:03    compiled Code at target/run/ticketmaster_transformation/models/core/distinct_data.sql
[2023-06-23T02:31:03.467+0000] {subprocess.py:93} INFO - [0m02:31:03
[2023-06-23T02:31:03.468+0000] {subprocess.py:93} INFO - [0m02:31:03  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
[2023-06-23T02:31:03.939+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-23T02:31:03.956+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-23T02:31:03.961+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_run, execution_date=20230623T022952, start_date=20230623T023056, end_date=20230623T023103
[2023-06-23T02:31:03.973+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2794 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 26203)
[2023-06-23T02:31:04.023+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-23T02:31:04.040+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
