[2023-06-23T01:57:35.102+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:56:31.696804+00:00 [queued]>
[2023-06-23T01:57:35.108+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:56:31.696804+00:00 [queued]>
[2023-06-23T01:57:35.109+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T01:57:35.109+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-23T01:57:35.110+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T01:57:35.117+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-23 01:56:31.696804+00:00
[2023-06-23T01:57:35.121+0000] {standard_task_runner.py:55} INFO - Started process 24491 to run task
[2023-06-23T01:57:35.124+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_run', 'scheduled__2023-06-23T01:56:31.696804+00:00', '--job-id', '2658', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmpiql9w7ox']
[2023-06-23T01:57:35.125+0000] {standard_task_runner.py:83} INFO - Job 2658: Subtask dbt_run
[2023-06-23T01:57:35.178+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:56:31.696804+00:00 [running]> on host 62cfed75eae1
[2023-06-23T01:57:35.227+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-23T01:56:31.696804+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-23T01:56:31.696804+00:00
[2023-06-23T01:57:35.228+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-23T01:57:35.229+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/ticketmaster_transformation && dbt run']
[2023-06-23T01:57:35.238+0000] {subprocess.py:86} INFO - Output:
[2023-06-23T01:57:36.771+0000] {subprocess.py:93} INFO - [0m01:57:36  Running with dbt=1.5.1
[2023-06-23T01:57:37.509+0000] {subprocess.py:93} INFO - [0m01:57:37  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 356 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-23T01:57:37.512+0000] {subprocess.py:93} INFO - [0m01:57:37
[2023-06-23T01:57:38.135+0000] {subprocess.py:93} INFO - [0m01:57:38  Concurrency: 4 threads (target='dev')
[2023-06-23T01:57:38.137+0000] {subprocess.py:93} INFO - [0m01:57:38
[2023-06-23T01:57:38.151+0000] {subprocess.py:93} INFO - [0m01:57:38  1 of 4 START sql table model twitter_kafka_pyspark_test.distinct_data .......... [RUN]
[2023-06-23T01:57:38.154+0000] {subprocess.py:93} INFO - [0m01:57:38  2 of 4 START sql table model twitter_kafka_pyspark_test.dm_events .............. [RUN]
[2023-06-23T01:57:38.156+0000] {subprocess.py:93} INFO - [0m01:57:38  3 of 4 START sql table model twitter_kafka_pyspark_test.my_first_dbt_model ..... [RUN]
[2023-06-23T01:57:40.751+0000] {subprocess.py:93} INFO - [0m01:57:40  3 of 4 OK created sql table model twitter_kafka_pyspark_test.my_first_dbt_model  [[32mCREATE TABLE (2.0 rows, 0 processed)[0m in 2.59s]
[2023-06-23T01:57:40.759+0000] {subprocess.py:93} INFO - [0m01:57:40  4 of 4 START sql view model twitter_kafka_pyspark_test.my_second_dbt_model ..... [RUN]
[2023-06-23T01:57:40.885+0000] {subprocess.py:93} INFO - [0m01:57:40  1 of 4 OK created sql table model twitter_kafka_pyspark_test.distinct_data ..... [[32mCREATE TABLE (1.0 rows, 0 processed)[0m in 2.72s]
[2023-06-23T01:57:40.972+0000] {subprocess.py:93} INFO - [0m01:57:40  BigQuery adapter: https://console.cloud.google.com/bigquery?project=global-maxim-338114&j=bq:US:fd0ea983-c814-42f3-bef7-5e1657a32f89&page=queryresults
[2023-06-23T01:57:40.981+0000] {subprocess.py:93} INFO - [0m01:57:40  2 of 4 ERROR creating sql table model twitter_kafka_pyspark_test.dm_events ..... [[31mERROR[0m in 2.82s]
[2023-06-23T01:57:41.870+0000] {subprocess.py:93} INFO - [0m01:57:41  4 of 4 OK created sql view model twitter_kafka_pyspark_test.my_second_dbt_model  [[32mCREATE VIEW (0 processed)[0m in 1.10s]
[2023-06-23T01:57:41.891+0000] {subprocess.py:93} INFO - [0m01:57:41
[2023-06-23T01:57:41.893+0000] {subprocess.py:93} INFO - [0m01:57:41  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 4.38 seconds (4.38s).
[2023-06-23T01:57:41.919+0000] {subprocess.py:93} INFO - [0m01:57:41
[2023-06-23T01:57:41.921+0000] {subprocess.py:93} INFO - [0m01:57:41  [31mCompleted with 1 error and 0 warnings:[0m
[2023-06-23T01:57:41.922+0000] {subprocess.py:93} INFO - [0m01:57:41
[2023-06-23T01:57:41.923+0000] {subprocess.py:93} INFO - [0m01:57:41  [33mDatabase Error in model dm_events (models/core/dm_events.sql)[0m
[2023-06-23T01:57:41.925+0000] {subprocess.py:93} INFO - [0m01:57:41    Unrecognized name: event_id at [14:8]
[2023-06-23T01:57:41.926+0000] {subprocess.py:93} INFO - [0m01:57:41    compiled Code at target/run/ticketmaster_transformation/models/core/dm_events.sql
[2023-06-23T01:57:41.927+0000] {subprocess.py:93} INFO - [0m01:57:41
[2023-06-23T01:57:41.929+0000] {subprocess.py:93} INFO - [0m01:57:41  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
[2023-06-23T01:57:42.371+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-23T01:57:42.389+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-23T01:57:42.393+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_run, execution_date=20230623T015631, start_date=20230623T015735, end_date=20230623T015742
[2023-06-23T01:57:42.407+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2658 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 24491)
[2023-06-23T01:57:42.460+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-23T01:57:42.476+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
